### ISSUE TITLE
Layer thickness (um) always show 0

### ISSUE THREAD

**Issue by jyehtw** [Godzil/WoWTools#1]
Manoël ,

Many Thanks your write this program for SparkMaker fans.

I want report the problem of the Layer thickness (um) always show 0, Would you help to check is my wrong?

[TKX]

**Comment by Godzil** [comment]
What is suppose to be the layer thickness?

Would it also be possible to have a sample wow file that exhibit the issue?

**Comment by Godzil** [comment]
Released version [v0.1.6,](https://github.com/Godzil/WoWTools/releases/tag/v0.1.6) could you check that it behave the same?

**Comment by Godzil** [comment]
Release [v0.2.0](https://github.com/Godzil/WoWTools/releases/tag/v0.2.0) show the rising distance value, does it show the proper value?

Have you set the rising distance to something else than 5mm? I would love to help and understand what is happening, but I do lack a lot of informations here, and not going to be easy to help with just "it is showing 0". The app works fine for me, even with the latest version of SparkStudio and layers set to 1µm (which the printer don't support), so I really don't know what is happening for you...

**Comment by jyehtw** [comment]
I had dobule check the layer thickness (um) show correct of wowviewer-0.2.0-win32 is Working.

**Comment by Godzil** [comment]
Ok thanks
